### ISSUE TITLE
Texture Error's

### ISSUE THREAD

**Issue by Eufranio** [runescapejon/AdventureBackpack2#19]
When i updated my modpack, and with it Adventure Backpacks to the latest version from releases, i get this error when joining a world/server:

```
[21:34:58] [Client thread/WARN]: Failed to load texture: adventurebackpack:textures/models/adventurepants_texture.png
java.io.FileNotFoundException: adventurebackpack:textures/models/adventurepants_texture.png
    at net.minecraft.client.resources.FallbackResourceManager.func_110536_a(SourceFile:51) ~[bqq.class:?]
    at net.minecraft.client.resources.SimpleReloadableResourceManager.func_110536_a(SimpleReloadableResourceManager.java:67) ~[brg.class:?]
    at net.minecraft.client.renderer.texture.SimpleTexture.func_110551_a(SourceFile:29) ~[bpu.class:?]
    at net.minecraft.client.renderer.texture.TextureManager.func_110579_a(TextureManager.java:94) [bqf.class:?]
    at net.minecraft.client.renderer.texture.TextureManager.func_110577_a(TextureManager.java:50) [bqf.class:?]
    at net.minecraft.client.renderer.entity.Render.func_110776_a(SourceFile:51) [bno.class:?]
    at net.minecraft.client.renderer.entity.RenderPlayer.func_77032_a(RenderPlayer.java:67) [bop.class:?]
    at net.minecraft.client.renderer.entity.RenderPlayer.func_77032_a(RenderPlayer.java:491) [bop.class:?]
    at net.minecraft.client.renderer.entity.RendererLivingEntity.func_76986_a(RendererLivingEntity.java:157) [boh.class:?]
    at net.minecraft.client.renderer.entity.RenderPlayer.func_76986_a(RenderPlayer.java:158) [bop.class:?]
    at net.minecraft.client.renderer.entity.RenderPlayer.func_76986_a(RenderPlayer.java:521) [bop.class:?]
    at net.minecraft.client.renderer.entity.RenderManager.func_147939_a(RenderManager.java:293) [bnn.class:?]
    at net.minecraft.client.renderer.entity.RenderManager.func_147940_a(RenderManager.java:276) [bnn.class:?]
    at net.minecraft.client.gui.inventory.GuiInventory.func_147046_a(SourceFile:91) [bfu.class:?]
    at net.minecraft.client.gui.inventory.GuiInventory.func_146976_a(SourceFile:60) [bfu.class:?]
    at net.minecraft.client.gui.inventory.GuiContainer.func_73863_a(GuiContainer.java:78) [bex.class:?]
    at net.minecraft.client.renderer.InventoryEffectRenderer.func_73863_a(InventoryEffectRenderer.java:38) [bfo.class:?]
    at net.minecraft.client.gui.inventory.GuiInventory.func_73863_a(SourceFile:47) [bfu.class:?]
    at net.minecraft.client.renderer.EntityRenderer.func_78480_b(EntityRenderer.java:1400) [blt.class:?]
    at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1001) [bao.class:?]
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:898) [bao.class:?]
    at net.minecraft.client.main.Main.main(SourceFile:148) [Main.class:?]
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_101]
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_101]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_101]
    at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_101]
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_101]
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_101]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_101]
    at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_101]
```

And my skin is glitched: http://prntscr.com/cmcrg9

**Comment by runescapejon** [comment]
can you test this without any mods just Adventurebackpack thanks

**Comment by Eufranio** [comment]
Tested with mods one by one, and the issue seems to be when using Adventure Backpacks + Cosmetic Armor Reworked, a incompatibility maybe.

**Comment by runescapejon** [comment]
Alright thanks you, I'll try my best to make it work

**Comment by Eufranio** [comment]
Happens when a Adventurer's Pants is renderer in my skin (both normal or cosmetic armor slots)

**Comment by runescapejon** [comment]
https://github.com/runescapejon/AdventureBackpack2/releases/tag/Beta-0.8eb28
